from tkinter import *

raiz = Tk()
raiz.title("Ventana de pruebas")
# raiz.resizable(True, 0)
raiz.iconbitmap("retriever.ico")
raiz.geometry("650x350")
raiz.config(bg = "#6666ff")
raiz.config(bd=45)
raiz.config(relief="sunken")
raiz.config(cursor="hand2")
miFrame = Frame()
miFrame.pack()
miFrame.config(bg="#e6e6ff")
miFrame.config(width="650",height="350")
miFrame.config(bd=35)
miFrame.config(relief="sunken")
miFrame.config(cursor="pirate")
raiz.mainloop()
